name: GitHub Action File Change Demo

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get all test, doc and src files that have changed
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            event-details:
              - 'plugins/event-details/package.json'
              - plugins/event-details/src/**
            event-backend:
              - plugins/event-backend/src/**
              - 'plugins/event-backend/package.json'
