name: GitHub Action File Change Demo

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get all test, doc and src files that have changed
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            event-details:
              - 'plugins/event-details/package.json'
              - plugins/event-details/src/**
            event-backend:
              - plugins/event-backend/src/**
              - 'plugins/event-backend/package.json'

      - name: Run step if event-details file(s) change
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-specific.outputs.event-details_any_changed == 'true'
        env:
          TEST_ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.event-details_all_changed_files }}
        run: |
          echo "One or more event details file(s) has changed."
          echo "List all the files that have changed: $TEST_ALL_CHANGED_FILES"

      - name: Run step if doc file(s) change
        if: steps.changed-files-specific.outputs.event-backend_any_changed == 'true'
        env:
          DOC_ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.event-backend_all_changed_files }}
        run: |
          echo "One or more event backend file(s) has changed."
          echo "List all the files that have changed: $DOC_ALL_CHANGED_FILES"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
